language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
# rbx on Travis cannot find ERB, disable until fixed again
#  - rbx-18mode
#  - rbx-19mode
#script: rake test test_us_ascii
notifications:
  email: false
  irc: "irc.freenode.org#asciidoctor"
